### ISSUE TITLE
Did you have figured out to use sam in iOS?

### ISSUE THREAD

**Issue by Innoyard** [tempdeltavalue/onnx_segment_anything_experiments#2]

**Comment by tempdeltavalue** [comment]
No :( 

onnx version of sam doesn't work (as I understand) in c++ and swift 

but I can advice this repo (but building of ncnn for iOS looks scary, a bit) 
https://github.com/FeiGeChuanShu/segment-anything-ncnn

**Comment by Innoyard** [comment]
😭 Did you have tried to change onnx to torch, and to coreML or onnx to coreML?

**Comment by tempdeltavalue** [comment]
@Innoyard Yeap, but coreml doesn't contain some torch functions
